import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";
import "./css/all.min.css";
import "./css/assets.css";
import "./css/content.css";
import "./css/portfolio.css";
import "./css/shortcodes.css";
import "./css/showcase.css";
import "./css/style.css";

import Preloader from "./_components/preloader";
import Navbar from "./_components/Navbar/navbar";
import Footer from "./_components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`hidden hidden-ball hero-below-caption smooth-scroll uppercase-text`}
        data-primary-color="#a3834b"
      >
        <main>
          <Preloader />
          <div className="cd-index cd-main-content">
            <div id="page-content" className="dark-content" data-bgcolor="#eee">
              <Navbar />
              <div id="content-scroll">
                {children}
                <Footer />
              </div>
            </div>
          </div>
        </main>


        {/* <div className="cd-cover-layer" />
        <div id="magic-cursor">
          <div id="ball">
            <div id="ball-drag-x" />
            <div id="ball-drag-y" />
            <div id="ball-loader" />
          </div>
        </div> */}
        <div id="clone-image">
          <div className="hero-translate" />
        </div>
        <div id="rotate-device" />

        <Script src="/js/jquery.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollTrigger.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollToPlugin.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/Draggable.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/EasePack.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/plugins/animation.gsap.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/5.0.0/imagesloaded.pkgd.min.js" />
        {/* <Script
          type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCpK1sWi3J3EbUOkF_K4-UHzi285HyFX5M&amp;sensor=false"
        /> */}
        <Script src="/js/clapatwebgl.js" />
        <Script src="/js/plugins.js" />
        <Script src="/js/common.js" />
        <Script src="/js/contact.js" />
        <Script src="/js/scripts.js" />
      </body>
    </html>
  );
}
