import type { Metadata } from "next";
import { Inter, DM_Sans} from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import ByAkira from "@/components/ByAkira";
import Navbar from "@/components/Navbar/Navbar";
import Navbar1 from "@/components/Navbar/Navbar1";


const dmSans = DM_Sans({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "antialiased")}>
        <Navbar1 />
        {children}
        {/* <ByAkira /> */}
      </body>
    </html>
  );
}
